CREATE TABLE IF NOT EXISTS public.images
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_images PRIMARY KEY,
    created         TIMESTAMP NOT NULL,
    updated         TIMESTAMP NOT NULL,
    file_name       VARCHAR(255) NOT NULL,
    file_type       VARCHAR(255) NOT NULL,
    target_width    BIGINT NOT NULL,
    target_height   BIGINT NOT NULL,
    uuid            VARCHAR(255) NOT NULL,
    status          VARCHAR(20) NOT NULL,
    data            BYTEA NULL,
    data_resize     BYTEA NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_uuid ON public.images(uuid);
